
// Generated by the FlatBuffers compiler. DO NOT EDIT.

#ifndef TENSORFLOW_LITE_SCHEMA_GENERATED_H_
#define TENSORFLOW_LITE_SCHEMA_GENERATED_H_

// This is a placeholder for schema_generated.h from the TensorFlow Lite source.
// In a real environment, this should be generated from schema.fbs using flatc.

namespace tflite {

// A very simplified version of Model just to satisfy inclusion
struct Model {
  int version;
};

}  // namespace tflite

#endif  // TENSORFLOW_LITE_SCHEMA_GENERATED_H_
